### ISSUE TITLE
RuntimeError:  attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage

### ISSUE THREAD

**Issue by vikoz** [rusty1s/pytorch_sparse#108]
Hi,

I'm having issues installing the latest version of torch-geometric from source, which seems to have an issue in torch-sparse.
(trying it on top of torch that is also from source)

The steps I've taken:

```bash
 2053  rm -rf .venv/
 2054  python3.8 -m venv .venv
 2055  . .venv/bin/activate
 2056  rm -rf ~/.cache/pip/
 2057  pip install wheel
 2058  pip install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
 2059  pip install git+https://github.com/pytorch/pytorch.git
 2060  pip install git+https://github.com/pytorch/vision.git
 2061  pip install git+https://github.com/rusty1s/pytorch_scatter.git git+https://github.com/rusty1s/pytorch_sparse.git git+https://github.com/rusty1s/pytorch_cluster.git git+https://github.com/rusty1s/pytorch_spline_conv.git
 2062  pip install git+https://github.com/rusty1s/pytorch_geometric.git
 2063  python
```

Tried to run:

```bash
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_geometric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.8/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File ".venv/lib/python3.8/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File ".venv/lib/python3.8/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File ".venv/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File ".venv/lib/python3.8/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File ".venv/lib/python3.8/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File ".venv/lib/python3.8/site-packages/torch_sparse/storage.py", line 21, in <module>
    class SparseStorage(object):
  File ".venv/lib/python3.8/site-packages/torch/jit/_script.py", line 964, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File ".venv/lib/python3.8/site-packages/torch/jit/_script.py", line 66, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError: 
attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
  File ".venv/lib/python3.8/site-packages/torch_sparse/storage.py", line 145
    def empty(self):
        self = SparseStorage.__new__(SparseStorage)
        self._row = None
        ~~~~~~~~~~~~~~~~ <--- HERE
        self._rowptr = None
        self._value = None
```

**Comment by rusty1s** [comment]
So you are installing PyTorch from master? Are you sure that `torch.jit.script` works in your PyTorch installation? It might be well able that the way PyTorch handles custom attributes in custom JIT classes has changed in the master branch, but we plan to only support the latest PyTorch release.

**Comment by vikoz** [comment]
Thanks for your reply!
Yes, I was trying to install from master, but then I had to make do with v1.7.1 branch. However, I will need to use latest version eventually since it has fixes the I need to run my model...
So, I was wondering, with PyTorch 1.8.0 coming out soon, when do you plan to adjust torch-geometric to support the latest version?

**Comment by rusty1s** [comment]
We usually release new versions within one week of a new PyTorch release.

**Comment by vikoz** [comment]
Thanks a lot, looking forward to the new version, then!

**Comment by rusty1s** [comment]
This is now fixed in master :)

**Comment by umesh-timalsina** [comment]
This is still an issue? I am trying to install `pytorch_sparse` with `python 3.8` in a conda environment?

**Comment by rusty1s** [comment]
I released a new version with this fixed a few days ago.

**Comment by LanceKnight** [comment]
Hello, I'm having the same issue still.

Traceback (most recent call last):
  File "tox21_col.py", line 4, in <module>
    from torch_geometric.datasets import MoleculeNet
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_sparse/storage.py", line 21, in <module>
    class SparseStorage(object):
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch/jit/_script.py", line 974, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
    torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
  File "/home/liuy69/.local/lib/python3.7/site-packages/torch_sparse/storage.py", line 145
    def empty(self):
        self = SparseStorage.__new__(SparseStorage)
        self._row = None
        ~~~~~~~~~~~~~~~~ <--- HERE
        self._rowptr = None


python version is 3.7.4

**Comment by rusty1s** [comment]
In case you do not use our wheels for installation, I recommend to install from master directly:
```python
pip install git+https://github.com/rusty1s/pytorch_sparse.git
```

**Comment by vikoz** [comment]
Hi @rusty1s ! Thanks, I verified that it works with PyTorch 1.8.0 :)
The only thing I had to change though is the following (not sure if that's by design or an issue).
I was installing `latest+cpu` versions from the following location for PyTorch 1.7.1:
`pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.7.0.html`
Now, I cannot do the same for 1.8.0, i.e. the following fails:
`pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.8.0.html`
But it works like this:
`pip install torch-scatter==2.0.6 -f https://pytorch-geometric.com/whl/torch-1.8.0+cpu.html`.

**Comment by TrentHawkins** [comment]
Hi, I have just built PyG from source, and get the same traceback upon `import torch_geometric`:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.9/site-packages/torch_geometric/__init__.py", line 2, in <module>
import torch_geometric.nn
File "/usr/lib/python3.9/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
from .data_parallel import DataParallel
File "/usr/lib/python3.9/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
from torch_geometric.data import Batch
File "/usr/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
from .data import Data
File "/usr/lib/python3.9/site-packages/torch_geometric/data/data.py", line 8, in <module>
from torch_sparse import coalesce, SparseTensor
File "/usr/lib/python3.9/site-packages/torch_sparse/__init__.py", line 34, in <module>
from .storage import SparseStorage  # noqa
File "/usr/lib/python3.9/site-packages/torch_sparse/storage.py", line 21, in <module>
class SparseStorage(object):
File "/usr/lib/python3.9/site-packages/torch/jit/_script.py", line 974, in script
_compile_and_register_class(obj, _rcb, qualified_name)
File "/usr/lib/python3.9/site-packages/torch/jit/_script.py", line 67, in _compile_and_register_class
torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
attribute assignment is not defined on __torch__.torch_sparse.storage.SparseStorage:
File "/usr/lib/python3.9/site-packages/torch_sparse/storage.py", line 145
def empty(self):
self = SparseStorage.__new__(SparseStorage)
self._row = None
~~~~~~~~~~~~~~~~ <--- HERE
self._rowptr = None
self._value = None
```
